// Hali real ma'lumot bilan to'ldirilmagan kategoriyalar — 
// karta ko'rinadi, lekin ochilmaydi ("Tez kunda")
export const LOCKED_CATEGORIES = new Set([
  // ==== AGRO ====
  "Agro-dron xizmati punkti",
  "Agro-texnika ijarasi punkti",
  "Asalari xo'jaligi",
  "Baliqchilik",
  "Biogumus sexi",
  "Dorivor o'simliklar plantatsiyasi",
  "Qo'ziqorinxona",
  "Quyosh panelli sug'orish stansiyasi",
  "Sovutgichli omborxona",

  // ==== DO'KONLAR ====
  "Apteka",
  "Avto ehtiyot qismlar",
  "Bolalar o'yinchoqlari va kiyimlari do'koni",
  "Gul va sovg'alar do'koni",
  "Kitob va kanselyariya do'koni",
  "Kosmetika va parfyumeriya do'koni",
  "Maishiy texnika va elektronika do'koni",
  "Mato va pardalar do'koni",
  "Mebel va interyer saloni",
  "Optika do'koni",
  "Qurilish materiallari do'koni",
  "Suvenirlar va milliy hunarmandchilik do'koni",
  "Velosiped va skuterlar do'koni",
  "Xojalik",
  "Zargarlik buyumlari do'koni",

  // ==== KO'NGILOCHAR ====
  "Akvapark / Suzish havzasi",
  "Bo'yoqli o'q otish maydoni",
  "Bolalar o'yin maydonchasi (Playzone)",
  "Bouling va bilyard klubi",
  "Ilmiy muzey va ko'rgazma zali",
  "Istirohat va attraksion bog'i",
  "Karaoke klubi",
  "Karting klubi",
  "Kinoteatr",
  "Mini-zoopark / Okeanarium",
  "Muz maydoni (Ice Rink)",
  "Ot sporti klubi",
  "SPA va sauna majmuasi",
  "Teatr va konsert zali",
  "Tog' kampingi / Dam olish maskani",
  "Virtual reallik va o'yin klubi",

  // ==== RESTORAN/KAFE ====
  "Bar",
  "Yapon taomlari kafesi",

  // ==== TA'LIM ====
  "Abituriyentlar tayyorlov markazi",
  "Avtomaktab",
  "Biznes boshqaruvi kurslari",
  "Chet elda o'qishga yordam beruvchi agentlik",
  "IT-akademiya",
  "Inklyuziv o'quv markazi",
  "Internet orqali dars beradigan platforma",
  "Kasb-hunar maktabi",
  "Logopediya va defektologiya markazi",
  "Malaka oshirish o'quv markazi",
  "Mental arifmetika markazi",
  "Musiqa va vokal maktabi",
  "Prezident maktabiga tayyorlov kursi",
  "Robototexnika to'garagi",
  "San'at va rasm chizish studiyasi",
  "Shaxmat klubi",
  "Xususiy bog'cha",
  "Xususiy maktab",
  "Yozgi bolalar oromgohi",

  // ==== XIZMAT KO'RSATISH ====
  "Avtoservis / Detailing markazi",
  "Bosmaxona",
  "Buxgalteriya va audit ofisi",
  "Dasturlash va sayt yaratish xizmati",
  "Dezinfeksiya xizmati markazi",
  "Go'zallik saloni / Barbershop",
  "Ijtimoiy tarmoqlarda reklama xizmati",
  "Kimyoviy tozalash (Ximchistka)",
  "Klining (Cleaning) kompaniyasi",
  "Ko'chmas mulk sotuvchisi (Rieltor)",
  "Maishiy texnika ta'mirlash ustaxonasi",
  "Qurilish va ta'mirlash kompaniyasi",
  "Santexnika ustaxonasi",
  "Tadbir tashkil qilish xizmati",
  "Tarjima va viza markazi",
  "Vetklinika / Gruming salon",
  "Xavfsizlik tizimlari do'koni",
  "Xodim tanlash agentligi",
  "Yuk tashish va logistika kompaniyasi",
  "Yuridik / Advokatlik firmasi",

  // ==== STARTAP VA TEXNOLOGIYALAR ====
  "Aqlli qishloq xo'jaligi xizmati",
  "Aqlli qurilmalar markazi",
  "Aqlli ta'lim platformasi",
  "Biologik tadqiqot laboratoriyasi",
  "Chiqindilarni qayta ishlash zavodi",
  "Internet orqali savdo platformasi",
  "Kompyuter o'yinlari klubi",
  "Logistika va yuk tashish startapi",
  "Masofadan ishlash platformasi",
  "Moliyaviy texnologiya kompaniyasi",
  "Onlayn maktab",
  "Onlayn psixologik yordam markazi",
  "Quyosh va shamol energiyasi kompaniyasi",
  "Raqamli valyuta markazi",
  "Robot yasash markazi",
  "Ruhiy salomatlik platformasi",
  "Sun'iy intellekt xizmatlari",
  "Umumiy ish maskani",
  "Virtual olam studiyasi",
  "Yangi tadbirkorlarga yordam markazi",
]);